version: '3.8'

services:
  app1:
    build: .
    container_name: cookie_auth_app1
    ports:
      - '8090:8080'
    restart: always
    environment:
      - ConnectionStrings__Redis=redis:6379

  app2:
    build: .
    container_name: cookie_auth_app2
    ports:
      - '8091:8080'
    restart: always
    environment:
      - ConnectionStrings__Redis=redis:6379

  app3:
    build: .
    container_name: cookie_auth_app3
    ports:
      - '8092:8080'
    restart: always
    environment:
      - ConnectionStrings__Redis=redis:6379

  app4:
    build: .
    container_name: cookie_auth_app4
    ports:
      - '8093:8080'
    restart: always
    environment:
      - ConnectionStrings__Redis=redis:6379

  app5:
    build: .
    container_name: cookie_auth_app5
    ports:
      - '8094:8080'
    restart: always
    environment:
      - ConnectionStrings__Redis=redis:6379

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '6380:6379'
    depends_on:
      - redisinsight
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis_viewer
    restart: always
    ports:
      - '8051:8001' # RedisInsight Web UI
