services:
  app:
    build: .
    container_name: cookie_auth_app
    ports:
      - '5000:8080'
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '7500:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
